#!/usr/bin/env python
# coding: utf-8

# ## Big Data Analytics: 
# 
# Collecting and analyzing large amounts of data generated by digital systems to uncover patterns and insights. Data mining?
# 
# 

# ### Introduction
# 
# Big Data and Big Data Analytics is a rapidly growing field that has the potential to revolutionize our understanding of the e.g. the brain and its functions.
# 
# With the advancements in technology, it is now possible to collect, store, and analyze massive amounts of data that would have been unfeasible a mere decade ago.
# 
# Big Data refers simply to large amounts of structured, semi-structured and unstructured data that researchers or organizations generate and collect. This data can come from a variety of sources such neuroimaging, genomics, and behavioral studies, but can also be collected from online sources such as social media, transactional systems, and more. The volume, variety, velocity and complexity of this data make it difficult to be processed and analyzed using traditional data processing methods.
# 
# Big Data Analytics in the sciences usually involves the use of advanced computational techniques and tools to extract meaningful insights from large amounts of data. Common applications involve the examination, transformation, cleaning, and modeling of large datasets to e.g. uncover hidden patterns or correlations.
# These insights can be used to understand the underlying mechanisms of brain function and behavior, as well as to develop new treatments for neurological disorders.
# 
# There are a variety of tools and technologies available for performing big data analytics in neuroscience. These include machine learning algorithms, neural networks, and graph databases, to name a few. These tools and technologies allow neuroscientists to process and analyze large amounts of data in real-time, and make informed decisions based on the insights gained from the analysis.
# 
# By leveraging the insights gained from big data analytics, neuroscientists can gain new insights into brain function and behavior, and develop new treatments for neurological disorders. If you are interested in pursuing a career in big data analytics in neuroscience, it is important to have a strong foundation in data analysis, statistics, and programming, as well as a background in neuroscience. But there are caveats, e.g. as even more so than in classical statistics it is important to understand the research requirements, design and implementation.
